import { StyleSheet } from 'react-native';
import { Tokens } from '../../../../theme/theme';

export const createStyles = (colors, isDarkMode) =>
  StyleSheet.create({
    scrollList: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 100,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 30,
      paddingTop: 40,
    },
    photoStack: {
      height: 260,
      width: 240,
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 35,
    },
    photoCard: {
      position: 'absolute',
      width: 140,
      height: 165,
      borderRadius: 16,
      borderWidth: 3,
      borderColor: '#FFFFFF',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 4,
    },
    stackImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    emptyTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 22,
      color: colors.textPrimary,
      textAlign: 'center',
      marginBottom: 8,
      letterSpacing: -0.4,
    },
    emptySubtitle: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 30,
    },
    emptyButton: {
      backgroundColor: '#1E5AE6',
      paddingHorizontal: 24,
      paddingVertical: 14,
      borderRadius: 24,
      shadowColor: '#1E5AE6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 4,
    },
    emptyButtonText: {
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 15,
    },
    cardContainer: {
      marginBottom: 10,
    },
    cardBackdrop: {
      height: 180,
      width: '100%',
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    photoDeck: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    deckPhoto: {
      width: 85,
      height: 110,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    deckPhotoImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    glassOverlay: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingHorizontal: 16,
    },
    glassBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    collectionLabelWrap: {
      marginTop: 12,
      paddingHorizontal: 4,
      marginBottom: 24,
      position: 'relative',
      alignItems: 'center',
    },
    titleRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    collectionTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 18,
      color: colors.textPrimary,
      letterSpacing: -0.2,
      textAlign: 'center',
    },
    collectionMeta: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 2,
      textAlign: 'center',
    },
    avatarsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
    },
    avatarCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      overflow: 'hidden',
    },
    avatarCountCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      backgroundColor: isDarkMode ? '#2D3748' : '#E2E8F0',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarCountText: {
      fontSize: 10,
      fontFamily: Tokens.typography.families.semiBold,
      color: colors.textSecondary,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 20,
      marginBottom: 12,
      paddingHorizontal: 20,
    },
    sectionTitleInline: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 18,
      color: colors.textPrimary,
    },
    fab: {
      position: 'absolute',
      bottom: 24,
      right: 20,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: '#ffffffff',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 6,
      zIndex: 999,
      borderColor: '#ee520fff',
      borderWidth: 1
    },
    // ── Stories Section ──
    storiesWrapper: {
      marginBottom: 20,
      paddingHorizontal: 4,
    },
    storiesTitle: {
      fontSize: 22,
      fontFamily: Tokens.typography.families.bold,
      color: colors.textPrimary,
      marginBottom: 12,
      paddingLeft: 4,
      letterSpacing: -0.4,
    },
    storiesScrollView: {
      flexDirection: 'row',
      paddingVertical: 4,
    },
    storyCard: {
      alignItems: 'center',
      width: 80,
      marginRight: 8,
    },
    storyAvatarWrapper: {
      width: 80,
      height: 80,
      borderRadius: 40,
      borderWidth: 2.2,
      borderColor: '#FF6B35',
      padding: 3,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      backgroundColor: isDarkMode ? '#1E1E1E' : '#FFFFFF',
    },
    storyAvatarImage: {
      width: '100%',
      height: '100%',
      borderRadius: 37,
    },
    storyAddBtn: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#FF6B35',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: isDarkMode ? '#121212' : '#FFFFFF',
    },
    storyNameText: {
      fontSize: 12,
      fontFamily: Tokens.typography.families.medium,
      color: colors.textPrimary,
      marginTop: 6,
      textAlign: 'center',
    },
    liveBadge: {
      position: 'absolute',
      bottom: -6,
      alignSelf: 'center',
      backgroundColor: '#EF4444',
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderRadius: 6,
      borderWidth: 1.2,
      borderColor: isDarkMode ? '#121212' : '#FFFFFF',
      zIndex: 5,
    },
    liveBadgeText: {
      fontSize: 8,
      fontFamily: Tokens.typography.families.bold,
      color: '#FFFFFF',
      textTransform: 'uppercase',
    },
  });
