export const strings = {
    header: {
        back: "Back",
        outfitCurated: "Outfit curated from 3 brands",
        titleFallback: "Streetwear Set – Urban Chill",
        descriptionFallback: "Outfit curated from 3 brands.",
    },
    productCard: {
        excludingExtras: "(Excluding extras)",
        buyWholeLook: "Buy the whole look(including extras).",
        allCombined: "(all items combined)",
        curatedVibe: "Curated look matching your vibe.",
        brandLabel: "Brand: ",
        sizeSelection: "Size Selection",
        topWear: "Top Wear",
        size: "Size",
        quantity: "Quantity",
        addExtras: "Add Extras",
        addExtrasSub: "(belt, cap, scarf)",
        addToCart: "Add to CaRT",
        buyNow: "Buy Now",
        addingToCart: "Adding to cart...",
        recommendProducts: "Recommend Products",
        readRefundPolicy: "Read Refund Policy",
    },
    tabs: {
        shippingInfo: "Shipping Info",
        howItWorks: "How It Works",
        productInfo: "Product Info",
    },
    shippingContent: {
        deliveryTimeTitle: "Delivery Time",
        deliveryTimeDesc: "Delivered within 3–5 business days by brand partner.",
        deliveryPartnerTitle: "Delivery Partner",
        deliveryPartnerDesc: "Shipped directly by H&M / Levis / Nike.",
        trackingTitle: "Tracking Info",
        trackingDesc: "You’ll receive tracking updates in your Order History once placed.",
        deliveryChargeTitle: "Delivery Charge",
        deliveryChargeDesc: "Free shipping for orders above ₹1,999.",
    },
    howItWorksContent: {
        selectLookTitle: "Select Your Look",
        selectLookDesc: "Choose full outfit or specific pieces.",
        checkoutTitle: "Checkout Securely",
        checkoutDesc: "Pay via UPI, Card, or Wallet.",
        orderConfirmedTitle: "Order Confirmed",
        orderConfirmedDesc: "We sync order with brand partner.",
        shippedByBrandTitle: "Shipped by Brand",
        shippedByBrandDesc: "Track updates inside the app.",
        refundAvailTitle: "Refund Available (12 hrs)",
        refundAvailDesc: "Cancel or refund within the first 12 hours.",
    },
    productInfoContent: {
        materialTitle: "Material",
        materialDesc: "100% Cotton (T-shirt), Stretch Denim (Jeans), Mesh (Shoes)",
        fitTypeTitle: "Fit Type",
        fitTypeDesc: "Regular Fit / Slim Fit / Relaxed",
        careTitle: "Care Instructions",
        careDesc: "Machine wash cold, tumble dry low.",
        colorOptTitle: "Color Options",
        colorOptDesc: "Black, Navy, Olive",
        madeInTitle: "Made In",
        madeInDesc: "Made in India / Imported",
        sustTitle: "Sustainability Note",
        sustDesc: "Eco-certified fabric used.",
    },
    refundContent: {
        refundReturnTitle: "Refund & Returns",
        refundReturnDesc: "After 12 hours, returns are managed by the brand. Initiate returns from your Order page.",
    },
    lists: {
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        tabsList: ["Shipping Info", "How It Works", "Product Info"],
    }
};