import { StyleSheet, Dimensions } from 'react-native';
import { Tokens } from '../../theme/theme';

const { width } = Dimensions.get('window');
const TOTAL_PADDINGS = Tokens.layout.paddingHorizontal * 2;
const TAB_CONTAINER_WIDTH = width - TOTAL_PADDINGS;
const EXACT_TAB_WIDTH = (TAB_CONTAINER_WIDTH - (4 * 2)) / 3;
const SINGLE_ROW_CHIP_WIDTH = (width - TOTAL_PADDINGS - Tokens.gaps.small * 5) / 7;
const RECOMMENDATION_CARD_WIDTH = (width - TOTAL_PADDINGS - Tokens.gaps.small * 2) / 3;

export const CAROUSEL_WIDTH = width - TOTAL_PADDINGS;
export const feedbackIconSize = Tokens.scaleAsset(12);

export const styles = StyleSheet.create({
    screenContainer: {
        flex: 1,
        backgroundColor: '#000000',
    },
    mainContainer: {
        flex: 1,
        width: '100%',
    },
    scrollContentContainer: {
        paddingHorizontal: Tokens.layout.paddingHorizontal,
        paddingTop: Tokens.gaps.medium,
        paddingBottom: 40,
    },
    backHeaderView: {
        width: '100%',
        height: 40,
        paddingHorizontal: Tokens.layout.paddingHorizontal,
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButtonView: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Tokens.gaps.small,
        height: '100%',
    },
    backButtonText: {
        fontFamily: Tokens.typography.families.medium,
        fontSize: Tokens.typography.sizes.body,
        color: '#E5E5E5',
    },
    headerView: {
        width: '100%',
        gap: Tokens.gaps.small,
        marginBottom: Tokens.gaps.large,
    },
    productTitleText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: Tokens.typography.sizes.title,
        lineHeight: Tokens.typography.lineHeights.title,
        color: '#FFFFFF',
    },
    productSubtitleText: {
        fontFamily: Tokens.typography.families.light,
        fontSize: Tokens.typography.sizes.body,
        lineHeight: Tokens.typography.lineHeights.body,
        color: '#E5E5E5',
    },
    postBoxView: {
        width: '100%',
        height: 389,
        borderRadius: 20,
        overflow: 'hidden',
        backgroundColor: '#1E1E20',
        position: 'relative',
        marginBottom: Tokens.gaps.large,
    },
    ImageCarousel: {
        position: 'absolute',
        bottom: 12,
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        gap: Tokens.gaps.small,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        paddingVertical: 4,
        paddingHorizontal: 12,
        borderRadius: 20,
    },
    indicatorDotInactive: {
        width: 12,
        height: 12,
        borderRadius: 6,
        borderWidth: 1.25,
        borderColor: '#CCCCCC',
    },
    indicatorDotActive: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    priceView: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        marginBottom: Tokens.gaps.xlarge,
    },
    priceText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 16,
        lineHeight: 26,
        color: '#FFFFFF',
    },
    excludingExtrasLabel: {
        fontFamily: Tokens.typography.families.regular,
        fontSize: 16,
        color: '#E5E5E5',
    },
    stockBadge: {
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 6,
        borderBottomColor: 'rgba(248, 45, 0, 0.15)',
    },
    stockText: {
        fontFamily: Tokens.typography.families.medium,
        fontSize: Tokens.typography.sizes.small,
        color: '#FFFFFF',
        textAlign: 'center',
    },
    gradientBorderOuterView: {
        padding: 1,
        borderRadius: 7,
        alignSelf: 'flex-start',
        borderTopLeftRadius: 3,
        borderTopRightRadius: 7,
        borderBottomRightRadius: 7,
        borderBottomLeftRadius: 13,
    },
    solidColorBackgroundMaskShield: {
        borderRadius: 6,
        overflow: 'hidden',
        backgroundColor: '#242426',
        borderTopLeftRadius: 2,
        borderTopRightRadius: 6,
        borderBottomRightRadius: 6,
        borderBottomLeftRadius: 12,
    },
    controlRowView: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: Tokens.gaps.large,
        width: '100%',
        paddingVertical: 4,
    },
    checkmarkToggleView: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#818181',
        backgroundColor: '#242426',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 2,
    },
    checkmarkToggleActiveView: {
        borderColor: 'transparent',
    },
    checkmarkInnerGradientView: {
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    comboDetailView: {
        flex: 1,
        gap: Tokens.gaps.small,
    },
    comboText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: Tokens.typography.sizes.body,
        color: '#FFFFFF',
    },
    comboPriceText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: Tokens.typography.sizes.body,
        color: '#FFFFFF',
    },
    allCombinedLabel: {
        fontFamily: Tokens.typography.families.regular,
        fontSize: 12,
        color: '#E5E5E5',
    },
    comboDescriptionText: {
        fontFamily: Tokens.typography.families.light,
        fontSize: Tokens.typography.sizes.body,
        lineHeight: Tokens.typography.lineHeights.body,
        color: '#E5E5E5',
    },
    brandsText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 12,
        color: '#ffffff',
        marginTop: 4,
    },
    brandView: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: Tokens.components.chipHeight,
        gap: Tokens.gaps.medium,
    },
    Divider: {
        width: '100%',
        height: 0,
        borderTopWidth: 1,
        borderColor: '#323537',
        marginVertical: Tokens.gaps.large,
    },
    Divider1: {
        width: '100%',
        height: 0,
        borderTopWidth: 0,
        borderColor: '#000000',
        marginVertical: Tokens.gaps.large,
    },
    SelectionView: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    SelectionText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 16,
        color: '#FFFFFF',
        marginBottom: Tokens.gaps.xlarge,
    },
    ClothingBox: {
        width: '100%',
        gap: Tokens.gaps.small,
        marginBottom: Tokens.gaps.xlarge,
    },
    clothingHeaderView: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Tokens.gaps.small,
    },
    clothTitleText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 14,
        color: '#FFFFFF',
        lineHeight: 24,
    },
    clothDescriptionText: {
        fontFamily: Tokens.typography.families.light,
        fontSize: 14,
        color: '#E5E5E5',
        marginBottom: Tokens.gaps.small,
    },
    sizeHeaderLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Tokens.gaps.small,
        marginBottom: 4,
    },
    sizeSectionTitleText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 13,
        color: '#FFFFFF',
    },
    sizeHorizontalRow: {
        flexDirection: 'row',
        gap: Tokens.gaps.small,
        width: '100%',
        marginBottom: Tokens.gaps.large,
    },
    sizeBoxButton: {
        width: SINGLE_ROW_CHIP_WIDTH,
        height: 38,
        borderRadius: 6,
        backgroundColor: '#242426',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 0.5,
        borderColor: '#D3CECE45',
    },
    sizeBoxButton1: {
        borderWidth: 1,
        borderColor: '#F8876C',
    },
    sizeItemText: {
        fontFamily: Tokens.typography.families.medium,
        fontSize: 12,
        color: '#B3B3B3',
    },
    sizeItemTextActive: {
        color: '#FFFFFF',
    },
    quantityText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 13,
        color: '#FFFFFF',
    },
    counterValueText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 13,
        color: '#FFFFFF',
    },
    quantityView: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        gap: Tokens.gaps.large,
    },
    counterActionLayoutGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: Tokens.gaps.medium,
    },
    counterTouch: {
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    counterBox: {
        width: 36,
        height: 36,
        borderRadius: 6,
        backgroundColor: '#1E1E20',
        alignItems: 'center',
        justifyContent: 'center',
    },
    addExtrasView: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: 32,
        marginVertical: Tokens.gaps.large,
    },
    addExtrasText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 14,
        color: '#FFFFFF',
    },
    addExtrasSubtext: {
        fontFamily: Tokens.typography.families.regular,
        color: '#ffffff',
        fontSize: 14,
    },
    buttonGroupBox: {
        width: '100%',
        gap: Tokens.gaps.large,
        marginTop: 8,
    },
    buttonGroupBox2: {
        width: '100%',
        height: Tokens.components.buttonHeight,
        borderRadius: Tokens.components.radiusButton,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonGroupBox1Text: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 16,
        color: '#FFFFFF',
    },
    tabView: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        height: 38,
        marginTop: Tokens.gaps.xlarge,
        marginBottom: Tokens.gaps.large,
        gap: 4,
    },
    buttonWrapper: {
        width: EXACT_TAB_WIDTH,
        height: 36,
    },
    activeBorderGradientView: {
        flex: 1,
        padding: 1,
        borderRadius: 9,
        overflow: 'hidden',
    },
    activeSolidBackgroundMaskShield: {
        flex: 1,
        borderRadius: 8,
        overflow: 'hidden',
        backgroundColor: '#242426',
    },
    activeGredientView: {
        flex: 1,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 2,
    },
    activeGredientView1: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 2,
    },
    categoryTabText: {
        fontFamily: Tokens.typography.families.medium,
        fontSize: 13,
        color: '#FFFFFF',
        textAlign: 'center',
    },
    categoryTabText1: {
        fontFamily: Tokens.typography.families.medium,
        fontSize: 13,
        color: '#E5E5E5',
        textAlign: 'center',
    },
    tabInfoView: {
        width: '100%',
        gap: Tokens.gaps.xlarge,
        paddingVertical: 4,
    },
    tabInfoView2: {
        width: '100%',
        gap: Tokens.gaps.large,
        paddingVertical: 4,
    },
    tabInfoView1: {
        width: '100%',
        gap: 6,
    },
    tabText1: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 13,
        color: '#FFFFFF',
    },
    tabText2: {
        fontFamily: Tokens.typography.families.light,
        fontSize: 13,
        lineHeight: Tokens.typography.lineHeights.body,
        color: '#E5E5E5',
    },
    refundPolicyText: {
        textDecorationLine: 'underline',
        color: '#FDABAC',
        fontFamily: Tokens.typography.families.medium,
        fontSize: 13,
    },
    recommendationView: {
        width: '100%',
        gap: Tokens.gaps.large,
        marginTop: Tokens.gaps.section,
    },
    recommendationText: {
        fontFamily: Tokens.typography.families.semiBold,
        fontSize: 20,
        lineHeight: 25,
        color: '#FFFFFF',
    },
    recommendationPRoductView: {
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    recommendationCardsView: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    recommendationItem: {
        width: RECOMMENDATION_CARD_WIDTH,
        height: 138,
        borderRadius: 12,
        backgroundColor: '#FFF3E8',
        overflow: 'hidden',
    },
    recommendationImage: {
        width: '100%',
        height: '100%',
    },
});