import { StyleSheet } from 'react-native';
import { Tokens } from '../../../../theme/theme';

export const createStyles = (colors, isDarkMode) =>
  StyleSheet.create({
    emptyButton: {
      backgroundColor: '#1E5AE6',
      paddingHorizontal: 24,
      paddingVertical: 14,
      borderRadius: 24,
      shadowColor: '#1E5AE6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 4,
    },
    emptyButtonText: {
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 15,
    },
    detailCollectionTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 24,
      color: colors.textPrimary,
      marginBottom: 8,
    },
    detailCollectionMeta: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 20,
      marginBottom: 12,
    },
    detailBadgeRow: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
    },
    statusBadgeText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 12,
    },
    detailEmptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 60,
      paddingHorizontal: 40,
    },
    detailEmptyText: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 14,
      color: colors.textTertiary,
      textAlign: 'center',
      marginTop: 12,
    },
    gridContainer: {
      paddingHorizontal: 6,
      marginTop: 20,
    },
    masonryContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
    },
    masonryColumn: {
      width: '49%',
      flexDirection: 'column',
    },
    gridItem: {
      width: '100%',
      borderRadius: 28,
      backgroundColor: isDarkMode ? '#1e1e2d' : '#F7FAFC',
      overflow: 'hidden',
      position: 'relative',
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 3,
    },
    gridImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    deleteOverlayBtn: {
      position: 'absolute',
      top: 10,
      left: 10,
      zIndex: 20,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      borderRadius: 18,
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statsOverlayRow: {
      position: 'absolute',
      bottom: 12,
      left: 10,
      right: 10,
      flexDirection: 'row',
      justifyContent: 'flex-start',
      gap: 6,
    },
    glassPill: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.25)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    glassPillText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontFamily: Tokens.typography.families.bold || 'System',
    },
    untagButton: {
      position: 'absolute',
      top: 6,
      right: 6,
      zIndex: 10,
    },
    gridCaptionBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    gridCaptionText: {
      fontSize: 11,
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.medium,
    },
    fab: {
      position: 'absolute',
      bottom: 24,
      right: 20,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: '#FF6B35',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 6,
      zIndex: 999,
    },
  });
