import { StyleSheet, Platform } from 'react-native';
import { Tokens } from '../../theme/theme';

export const createStyles = (colors, isDarkMode) =>
  StyleSheet.create({
    screenContainer: {
      flex: 1,
      backgroundColor: isDarkMode ? colors.bg : '#FFFFFF',
    },
    mainContainer: {
      flex: 1,
    },
    // Mockup Header styles
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      height: 60,
    },
    headerLeft: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDarkMode ? '#2D3748' : '#E2E8F0',
      overflow: 'hidden',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    headerSearchWrap: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDarkMode ? '#2D3748' : '#F1F5F9',
      borderRadius: 16,
      marginHorizontal: 12,
      paddingHorizontal: 12,
      height: 38,
    },
    headerSearchInput: {
      flex: 1,
      fontSize: 14,
      fontFamily: Tokens.typography.families.medium,
      padding: 0,
    },
    circleButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDarkMode ? '#2D3748' : '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    // Trip Selector Dropdown in header
    tripSelectorBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: isDarkMode ? '#2D3748' : '#F7FAFC',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    tripSelectorText: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 16,
      color: colors.textPrimary,
    },
    // Scroll List
    scrollList: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 100, // Safe padding for FAB and Custom TabBar
    },
    // Empty State styles
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 30,
      paddingTop: 40,
    },
    photoStack: {
      height: 260,
      width: 240,
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 35,
    },
    photoCard: {
      position: 'absolute',
      width: 140,
      height: 165,
      borderRadius: 16,
      borderWidth: 3,
      borderColor: '#FFFFFF',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 4,
    },
    stackImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    emptyTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 22,
      color: colors.textPrimary,
      textAlign: 'center',
      marginBottom: 8,
      letterSpacing: -0.4,
    },
    emptySubtitle: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 30,
    },
    emptyButton: {
      backgroundColor: '#1E5AE6',
      paddingHorizontal: 24,
      paddingVertical: 14,
      borderRadius: 24,
      shadowColor: '#1E5AE6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 4,
    },
    emptyButtonText: {
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 15,
    },
    // Collection list styles
    cardContainer: {
      marginBottom: 10,
    },
    cardBackdrop: {
      height: 180,
      width: '100%',
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    photoDeck: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    deckPhoto: {
      width: 85,
      height: 110,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    deckPhotoImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    glassOverlay: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingHorizontal: 16,
    },
    glassBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    collectionLabelWrap: {
      marginTop: 12,
      paddingHorizontal: 4,
      marginBottom: 24,
      position: 'relative',
      alignItems: 'center',
    },
    titleRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    collectionTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 18,
      color: colors.textPrimary,
      letterSpacing: -0.2,
      textAlign: 'center',
    },
    editCollectionBtn: {
      padding: 4,
    },
    collectionMeta: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 2,
      textAlign: 'center',
    },
    avatarsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
    },
    avatarCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      overflow: 'hidden',
    },
    avatarCountCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      backgroundColor: isDarkMode ? '#2D3748' : '#E2E8F0',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarCountText: {
      fontSize: 10,
      fontFamily: Tokens.typography.families.semiBold,
      color: colors.textSecondary,
    },
    // FAB (Floating Action Button)
    fab: {
      position: 'absolute',
      bottom: 24,
      right: 20,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: '#FF6B35',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 6,
      zIndex: 999,
    },
    // Upload Form Styles (Modernized)
    uploadContainer: {
      flexGrow: 1,
      padding: 20,
    },
    imagePreviewWrap: {
      width: '100%',
      height: 260,
      borderRadius: 24,
      backgroundColor: isDarkMode ? '#2D3748' : '#F7FAFC',
      borderWidth: 2,
      borderColor: colors.divider,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      marginBottom: 20,
    },
    previewImg: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    placeholderText: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 8,
    },
    inputGroup: {
      marginBottom: 16,
    },
    label: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 6,
    },
    textInput: {
      height: 48,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.divider,
      paddingHorizontal: 16,
      fontFamily: Tokens.typography.families.medium,
      fontSize: 14,
      color: colors.textPrimary,
    },
    pickerRow: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 4,
    },
    pickerOption: {
      flex: 1,
      height: 44,
      borderRadius: 12,
      borderWidth: 1.5,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pickerOptionText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 13,
    },
    actionBtn: {
      height: 52,
      borderRadius: 26,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 24,
    },
    actionBtnText: {
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 15,
    },
    // Modal & Sheet layout
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 40,
      backgroundColor: isDarkMode ? '#1A202C' : '#FFFFFF',
    },
    modalIndicator: {
      width: 40,
      height: 4,
      backgroundColor: isDarkMode ? '#4A5568' : '#CBD5E0',
      borderRadius: 2,
      alignSelf: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 20,
      color: colors.textPrimary,
      marginBottom: 20,
    },
    // Bottom Sheet list items (Trips / Collection Menu)
    sheetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    sheetRowText: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 15,
      color: colors.textPrimary,
    },
    // Section Headers
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 20,
      marginBottom: 12,
      paddingHorizontal: 20,
    },
    sectionTitleInline: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 18,
      color: colors.textPrimary,
    },
    sectionTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 18,
      color: colors.textPrimary,
      marginTop: 20,
      marginBottom: 12,
      paddingHorizontal: 20,
    },
    // Grid list layout (Trips & Collection details)
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 16,
      justifyContent: 'space-between',
    },
    gridItem: {
      width: '48%', // Fits 2 columns
      aspectRatio: 0.8, // Taller vertical cards matching mockup
      borderRadius: 20,
      backgroundColor: isDarkMode ? '#2D3748' : '#F7FAFC',
      overflow: 'hidden',
      position: 'relative',
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    gridImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    badgeOverlay: {
      position: 'absolute',
      top: 6,
      right: 6,
      backgroundColor: 'rgba(0,0,0,0.5)',
      paddingHorizontal: 4,
      paddingVertical: 2,
      borderRadius: 6,
    },
    badgeText: {
      fontSize: 10,
    },
    untagButton: {
      position: 'absolute',
      top: 6,
      right: 6,
      zIndex: 10,
    },
    gridCaptionBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    gridCaptionText: {
      fontSize: 11,
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.medium,
    },
    // Collection Details Screen
    detailCollectionTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 24,
      color: colors.textPrimary,
      marginBottom: 8,
    },
    detailCollectionMeta: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 20,
      marginBottom: 12,
    },
    detailBadgeRow: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
    },
    statusBadgeText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 12,
    },
    detailEmptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 60,
      paddingHorizontal: 40,
    },
    detailEmptyText: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 14,
      color: colors.textTertiary,
      textAlign: 'center',
      marginTop: 12,
    },
    // Full screen viewer styles
    viewerOverlay: {
      flex: 1,
      backgroundColor: '#000000',
      justifyContent: 'center',
      alignItems: 'center',
    },
    viewerCloseBtn: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 60 : 30,
      right: 20,
      zIndex: 10,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    viewerContent: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    viewerImage: {
      width: '94%',
      height: '70%',
      resizeMode: 'contain',
    },
    viewerCaptionBox: {
      position: 'absolute',
      bottom: Platform.OS === 'ios' ? 60 : 40,
      left: 20,
      right: 20,
      padding: 16,
      borderRadius: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.15)',
    },
    viewerCaptionText: {
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.medium,
      fontSize: 15,
      lineHeight: 22,
    },
    viewerBadgeRow: {
      flexDirection: 'row',
      marginTop: 10,
    },
    viewerBadge: {
      color: '#FF6B35',
      fontFamily: Tokens.typography.families.bold,
      fontSize: 12,
    },
  });