import { StyleSheet } from 'react-native';
import { Tokens } from '../../theme/theme';

export const createStyles = (colors, isDarkMode) =>
  StyleSheet.create({
    screenContainer: {
      flex: 1,
      backgroundColor: isDarkMode ? colors.bg : '#F8FAFC',
    },
    safeArea: {
      flex: 1,
    },
    scrollContainer: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 30,
    },
    cardContainer: {
      width: '90%',
      maxWidth: Tokens.layout.maxWidth,
      backgroundColor: isDarkMode ? colors.surface : '#FFFFFF',
      borderRadius: 24,
      paddingHorizontal: 24,
      paddingVertical: 32,
      alignItems: 'center',
      borderWidth: isDarkMode ? 1.5 : 0,
      borderColor: colors.border,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.05,
      shadowRadius: 12,
      elevation: isDarkMode ? 0 : 3,
    },
    avatarCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: isDarkMode ? colors.border : '#F3F4F6',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    logoImage: {
      width: 120,
      height: 120,
      marginBottom: 16,
    },
    titleText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 26,
      lineHeight: 32,
      color: colors.textPrimary,
      fontWeight: '800',
      letterSpacing: -0.5,
      marginBottom: 24,
    },
    inputFieldsContainer: {
      width: '100%',
      gap: 18,
      marginBottom: 24,
    },
    formGroup: {
      width: '100%',
      gap: 8,
    },
    labelRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 4,
    },
    fieldLabel: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 14,
      color: colors.textSecondary,
    },
    forgotPasswordLink: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 13,
      color: '#FF6B35',
    },
    forgotPasswordContainer: {
      alignSelf: 'flex-end',
      marginTop: 6,
      paddingHorizontal: 4,
    },
    inputFieldContainer: {
      width: '100%',
      height: Tokens.components.inputHeight,
      borderRadius: 12,
      backgroundColor: isDarkMode ? colors.bg : '#FFFFFF',
      borderWidth: 1.5,
      borderColor: isDarkMode ? colors.border : '#E5E7EB',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
    },
    inputIcon: {
      marginRight: 12,
    },
    inputText: {
      flex: 1,
      fontFamily: Tokens.typography.families.medium,
      fontSize: 15,
      color: colors.textPrimary,
      padding: 0,
      height: '100%',
    },
    eyeButton: {
      width: 28,
      height: 28,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    submitButton: {
      width: '100%',
      height: Tokens.components.buttonHeight,
      borderRadius: 12,
      backgroundColor: '#FF6B35',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    submitButtonText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 16,
      color: '#FFFFFF',
    },
    dividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      marginVertical: 18,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: isDarkMode ? colors.border : '#E5E7EB',
    },
    dividerText: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 13,
      color: colors.textSecondary,
      paddingHorizontal: 12,
    },
    socialsContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 20,
      width: '100%',
      marginBottom: 28,
    },
    socialRoundButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: isDarkMode ? colors.surface : '#FFFFFF',
      borderWidth: 1.5,
      borderColor: isDarkMode ? colors.border : '#E5E7EB',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0 : 0.05,
      shadowRadius: 4,
      elevation: isDarkMode ? 0 : 1,
    },
    footerContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    footerText: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 14,
      color: colors.textSecondary,
    },
    footerLinkText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 14,
      color: '#FF6B35',
    },
  });