import { StyleSheet } from 'react-native';
import { Tokens } from '../../theme/theme';

export const createStyles = (COLORS, GRADIENTS, SHADOWS, RADIUS) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 56,
    position: 'relative',
    marginTop: 8,
  },
  backButton: {
    position: 'absolute',
    left: 16,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: Tokens.typography.families.semiBold,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  profileWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 24,
    marginBottom: 16,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarInitial: {
    fontSize: 28,
    color: COLORS.textPrimary,
    fontWeight: '800',
  },
  userMeta: {
    marginLeft: 16,
    justifyContent: 'center',
  },
  userName: {
    fontSize: 20,
    fontFamily: Tokens.typography.families.semiBold,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  userEmail: {
    fontSize: 14,
    fontFamily: Tokens.typography.families.regular,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  settingIcon: {
    marginRight: 18,
    width: 24,
    textAlign: 'center',
  },
  settingLabel: {
    fontSize: 16,
    fontFamily: Tokens.typography.families.medium,
    fontWeight: '500',
    color: COLORS.textPrimary,
  },
  deleteLink: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
    marginBottom: 48,
    paddingVertical: 12,
  },
  deleteLinkText: {
    color: COLORS.danger,
    fontSize: 14,
    fontFamily: Tokens.typography.families.medium,
    textDecorationLine: 'underline',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(30, 41, 59, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    backgroundColor: COLORS.card,
    borderRadius: 24,
    padding: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
    marginBottom: 16,
  },
  ringtoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  ringtoneRowActive: {
    backgroundColor: COLORS.primaryGhost,
  },
  ringtoneText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  ringtoneTextActive: {
    color: COLORS.primary,
  },
});
