import { StyleSheet, Platform } from 'react-native';
import { Tokens } from '../../../../theme/theme';

export const createStyles = (colors, isDarkMode) =>
  StyleSheet.create({
    uploadContainer: {
      flexGrow: 1,
      padding: 20,
      paddingBottom: 40,
    },
    collectionInfoWrap: {
      marginBottom: 16,
    },
    collectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
    },
    collectionNameText: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 16,
      color: '#FF6B35',
    },
    dashedDropZone: {
      width: '100%',
      backgroundColor: isDarkMode ? 'rgba(99, 102, 241, 0.03)' : 'rgba(99, 102, 241, 0.05)',
      borderRadius: 24,
      borderWidth: 2,
      borderColor: isDarkMode ? '#4F46E5' : '#818CF8',
      borderStyle: 'dashed',
      paddingVertical: 32,
      paddingHorizontal: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
    },
    dropZoneTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 18,
      textAlign: 'center',
      color: colors.textPrimary,
      marginTop: 16,
      lineHeight: 24,
    },
    boldPrimaryText: {
      color: '#6366F1',
    },
    dropZoneSubtitle: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 13,
      textAlign: 'center',
      color: colors.textSecondary,
      marginTop: 8,
    },
    browseLink: {
      fontFamily: Tokens.typography.families.bold,
      color: '#6366F1',
      textDecorationLine: 'underline',
    },
    browsePillBtn: {
      backgroundColor: '#FF6B35',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      marginTop: 16,
      shadowColor: '#FF6B35',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 2,
    },
    browsePillBtnText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 13,
      color: '#FFFFFF',
    },
    stagingSection: {
      marginBottom: 20,
    },
    stagedListScroll: {
      paddingVertical: 8,
      gap: 12,
    },
    stagedImageContainer: {
      width: 80,
      height: 80,
      borderRadius: 12,
      overflow: 'visible',
      position: 'relative',
      marginRight: 10,
      borderWidth: 1,
      borderColor: colors.divider,
    },
    stagedImage: {
      width: '100%',
      height: '100%',
      borderRadius: 11,
      resizeMode: 'cover',
    },
    deleteBadge: {
      position: 'absolute',
      top: -6,
      right: -6,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: '#EF4444',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    inputGroup: {
      marginBottom: 16,
    },
    label: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 6,
    },
    textInput: {
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.divider,
      paddingHorizontal: 16,
      fontFamily: Tokens.typography.families.medium,
      fontSize: 14,
      color: colors.textPrimary,
    },
    pickerRow: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 4,
    },
    pickerOption: {
      flex: 1,
      height: 44,
      borderRadius: 12,
      borderWidth: 1.5,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pickerOptionText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 13,
    },
    actionBtn: {
      height: 52,
      borderRadius: 26,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    actionBtnText: {
      color: '#FFFFFF',
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 15,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: isDarkMode ? '#1E293B' : '#FFFFFF',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    },
    modalDragBar: {
      width: 40,
      height: 5,
      borderRadius: 2.5,
      backgroundColor: colors.divider,
      alignSelf: 'center',
      marginBottom: 20,
    },
    modalSheetTitle: {
      fontFamily: Tokens.typography.families.bold,
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 16,
      textAlign: 'center',
    },
    sheetOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderColor: colors.divider,
      gap: 12,
    },
    sheetOptionText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 14,
      color: colors.textPrimary,
    },
  });
