import { StyleSheet } from 'react-native';
import { Tokens } from '../../theme/theme';

export const createStyles = (colors, isDarkMode) =>
  StyleSheet.create({
    screenContainer: {
      flex: 1,
      backgroundColor: isDarkMode ? colors.bg : '#F8FAFC',
    },
    safeArea: {
      flex: 1,
    },
    scrollContainer: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 30,
    },
    cardContainer: {
      width: '90%',
      maxWidth: Tokens.layout.maxWidth,
      backgroundColor: isDarkMode ? colors.surface : '#FFFFFF',
      borderRadius: 24,
      paddingHorizontal: 24,
      paddingVertical: 32,
      alignItems: 'center',
      borderWidth: isDarkMode ? 1.5 : 0,
      borderColor: colors.border,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.05,
      shadowRadius: 12,
      elevation: isDarkMode ? 0 : 3,
    },
    avatarCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: isDarkMode ? colors.border : '#F3F4F6',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    logoImage: {
      width: 120,
      height: 120,
      marginBottom: 16,
    },
    titleText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 26,
      lineHeight: 32,
      color: colors.textPrimary,
      fontWeight: '800',
      letterSpacing: -0.5,
      marginBottom: 24,
    },
    inputFieldsContainer: {
      width: '100%',
      gap: 16,
      marginBottom: 24,
    },
    formGroup: {
      width: '100%',
      gap: 6,
    },
    labelRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 4,
    },
    fieldLabel: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 14,
      color: colors.textSecondary,
    },
    inputFieldContainer: {
      width: '100%',
      height: Tokens.components.inputHeight,
      borderRadius: 12,
      backgroundColor: isDarkMode ? colors.bg : '#FFFFFF',
      borderWidth: 1.5,
      borderColor: isDarkMode ? colors.border : '#E5E7EB',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
    },
    inputIcon: {
      marginRight: 12,
    },
    inputText: {
      flex: 1,
      fontFamily: Tokens.typography.families.medium,
      fontSize: 15,
      color: colors.textPrimary,
      padding: 0,
      height: '100%',
    },
    eyeButton: {
      width: 28,
      height: 28,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    passwordView: {
      width: '100%',
      gap: 12,
    },
    strengthView: {
      width: '100%',
      gap: 6,
      marginTop: 4,
      paddingHorizontal: 4,
    },
    strengthTextRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
    },
    passwordStrengthText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 13,
      color: colors.textPrimary,
    },
    strongValueText: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 12,
      color: colors.textSecondary,
    },
    navigationMeterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      height: 6,
      gap: 6,
      marginTop: 2,
    },
    meterBar: {
      flex: 1,
      height: 6,
      borderRadius: 3,
      backgroundColor: isDarkMode ? colors.border : '#E5E7EB',
    },
    requirementView: {
      width: '100%',
      gap: 10,
      marginTop: 8,
      paddingHorizontal: 4,
    },
    requirementText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 13,
      color: colors.textPrimary,
    },
    indicationView: {
      width: '100%',
      gap: 6,
    },
    indicationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    iconBoxCenter: {
      width: 16,
      height: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    requirementItemText: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 13,
      color: colors.textSecondary,
    },
    requirementSuccessText: {
      color: '#38B2AC',
    },
    infoBarView: {
      width: '100%',
      marginTop: 6,
    },
    infoBarInnerView: {
      width: '100%',
      borderRadius: 12,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDarkMode ? 'rgba(255, 107, 53, 0.08)' : 'rgba(255, 107, 53, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 107, 53, 0.15)',
    },
    infoIconSpacing: {
      marginRight: 10,
    },
    infoBarText: {
      flex: 1,
      fontFamily: Tokens.typography.families.medium,
      fontSize: 12.5,
      color: colors.textPrimary,
    },
    passwordMatchedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      width: '100%',
      marginTop: 4,
      paddingHorizontal: 4,
    },
    passwordMatchedText: {
      fontFamily: Tokens.typography.families.medium,
      fontSize: 12.5,
      color: colors.textSecondary,
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      width: '100%',
      marginTop: 8,
      paddingHorizontal: 4,
    },
    checkmarkBoxActive: {
      width: 22,
      height: 22,
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#FF6B35',
    },
    checkmarkBoxInactive: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: isDarkMode ? colors.border : '#D1D5DB',
      backgroundColor: isDarkMode ? colors.bg : '#FFFFFF',
    },
    checkboxLabel: {
      flex: 1,
      fontFamily: Tokens.typography.families.medium,
      fontSize: 13,
      color: colors.textPrimary,
      lineHeight: 18,
    },
    submitButton: {
      width: '100%',
      height: Tokens.components.buttonHeight,
      borderRadius: 12,
      backgroundColor: '#FF6B35',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 12,
      marginBottom: 20,
    },
    submitButtonText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 16,
      color: '#FFFFFF',
    },
    submitLoadingBg: {
      backgroundColor: '#FF6B35',
    },
    dividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      marginVertical: 18,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: isDarkMode ? colors.border : '#E5E7EB',
    },
    dividerText: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 13,
      color: colors.textSecondary,
      paddingHorizontal: 12,
    },
    socialsContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 20,
      width: '100%',
      marginBottom: 28,
    },
    socialRoundButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: isDarkMode ? colors.surface : '#FFFFFF',
      borderWidth: 1.5,
      borderColor: isDarkMode ? colors.border : '#E5E7EB',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0 : 0.05,
      shadowRadius: 4,
      elevation: isDarkMode ? 0 : 1,
    },
    footerContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    footerText: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 14,
      color: colors.textSecondary,
    },
    footerLinkText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 14,
      color: '#FF6B35',
    },
    termsLink: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 13,
      color: '#FF6B35',
      textDecorationLine: 'underline',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      width: '100%',
      maxWidth: 400,
      maxHeight: '75%',
      backgroundColor: isDarkMode ? colors.surface : '#FFFFFF',
      borderRadius: 20,
      padding: 24,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.15,
      shadowRadius: 15,
      elevation: 10,
      borderWidth: isDarkMode ? 1.5 : 0,
      borderColor: colors.border,
    },
    modalTitle: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 20,
      color: colors.textPrimary,
      marginBottom: 16,
      fontWeight: '700',
    },
    modalScroll: {
      marginBottom: 20,
    },
    modalText: {
      fontFamily: Tokens.typography.families.regular,
      fontSize: 14,
      lineHeight: 22,
      color: colors.textSecondary,
    },
    modalCloseButton: {
      width: '100%',
      height: 46,
      borderRadius: 12,
      backgroundColor: '#FF6B35',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalCloseButtonText: {
      fontFamily: Tokens.typography.families.semiBold,
      fontSize: 15,
      color: '#FFFFFF',
    },
    modalLoaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      minHeight: 150,
    },
  });
