import { StyleSheet } from 'react-native';
import { Tokens } from '../../theme/theme';


export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  safeArea: {
    flex: 1,
  },
  scrollContainer: {
    alignItems: 'center',
  },
  mainContainer: {
    width: '100%',
    maxWidth: Tokens.layout.maxWidth,
    paddingVertical: Tokens.layout.paddingVertical,
    paddingHorizontal: Tokens.layout.paddingHorizontal,
    alignItems: 'center',
  },
  header: {
    width: '100%',
    marginBottom: Tokens.gaps.separator,
    gap: Tokens.gaps.large,
  },
  titleText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.title,
    lineHeight: Tokens.typography.lineHeights.title,
    color: '#070707',
  },
  subtitleText: {
    fontFamily: Tokens.typography.families.light,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#131313',
  },
  inputFieldsContainer: {
    width: '100%',
    gap: Tokens.gaps.xlarge,
    marginBottom: Tokens.gaps.section,
  },
  inputOuterView: {
    width: '100%',
    height: Tokens.components.inputHeight,
    borderRadius: Tokens.components.radiusInput,
    overflow: 'hidden',
  },
  inputGradientBackground: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#323537',
    borderRadius: Tokens.components.radiusInput,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  inputText: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.body,
    color: '#E5E5E5',
    height: '100%',
  },
  passwordView: {
    width: '100%',
    gap: Tokens.gaps.large,
  },
  eyeButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: Tokens.gaps.small,
  },
  strengthView: {
    width: '100%',
    gap: Tokens.gaps.small,
  },
  strengthTextRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 24,
  },
  passwordStrengthText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#181818',
  },
  strongValueText: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#181818',
  },
  navigationMeterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 16,
    gap: 6,
  },
  meterBar: {
    flex: 1,
    height: Tokens.components.barMetricHeight,
    borderRadius: Tokens.components.radiusBar,
    borderWidth:1,

  },
  requirementView: {
    width: '100%',
    gap: Tokens.gaps.medium,
    marginTop: Tokens.gaps.small,
  },
  requirementText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#3f3f3f',
  },
  indicationView: {
    width: '100%',
    gap: Tokens.gaps.small,
  },
  indicationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Tokens.gaps.small,
    height: 20,
  },
  iconBoxCenter: {
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  requirementItemText: {
    fontFamily: Tokens.typography.families.regular,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#454444',
  },
  infoBarView: {
    width: '100%',
    minHeight: Tokens.components.infoMinHeight,
    borderRadius: Tokens.components.radiusInput,
    overflow: 'hidden',
  },
  infoBarInnerView: {
    flex: 1,
    borderWidth: 0.5,
    borderColor: '#323537',
    borderRadius: Tokens.components.radiusInput,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoIconSpacing: {
    marginRight: Tokens.gaps.medium,
  },
  infoBarText: {
    flex: 1,
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#000000',
  },
  inputView: {
    width: '100%',
    gap: Tokens.gaps.small,
  },
  passwordMatchedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    height: 20,
    paddingHorizontal: 4,
  },
  passwordMatchedText: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#000000',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Tokens.gaps.small,
    width: '100%',
    height: 24,
    marginTop: Tokens.gaps.small,
  },
  checkmarkBoxActive: {
    width: 24,
    height: 24,
    borderRadius: Tokens.components.radiusSmall,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(251, 147, 96, 0.64)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 4,
  },
  checkmarkBoxInactive: {
    width: 24,
    height: 24,
    borderRadius: Tokens.components.radiusSmall,
    backgroundColor: '#323537',
    borderWidth: 1,
    borderColor: '#818181',
  },
  checkboxLabel: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#000000',
  },
  continueButtonView: {
    width: '100%',
    gap: Tokens.gaps.large,
    alignItems: 'center',
  },
  primaryButtonWrapper: {
    width: '100%',
    height: Tokens.components.buttonHeight,
    borderRadius: Tokens.components.radiusButton,
    shadowColor: 'rgba(251, 147, 96, 0.64)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButton: {
    flex: 1,
    borderRadius: Tokens.components.radiusButton,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButtonText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.subButton,
    lineHeight: Tokens.typography.lineHeights.title,
    color: '#FFFFFF',
  },
  socialsView: {
    width: '100%',
    gap: Tokens.gaps.large,
    alignItems: 'center',
  },
  orSignUpWithText: {
    fontFamily: Tokens.typography.families.regular,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#242424',
    marginVertical: 4,
  },
  socialButton: {
    width: '100%',
    height: Tokens.components.buttonHeight,
    backgroundColor: '#323537',
    borderWidth: 0.5,
    borderColor: '#818181',
    borderRadius: Tokens.components.radiusButton,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialIconLayout: {
    marginRight: 5,
  },
  socialButtonText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.subButton,
    lineHeight: Tokens.typography.lineHeights.title,
    color: '#FFFFFF',
  },
  footerView: {
    width: '100%',
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    flexDirection: 'row',
  },
  loginText: {
    marginTop: 7,
  },
  footerText: {
    fontFamily: Tokens.typography.families.regular,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#171616',
    textAlign: 'center',
  },
  loginLink: {
    fontFamily: Tokens.typography.families.semiBold,
    textDecorationLine: 'underline',
    color: '#121212',
  },
  checkmarkCircleWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: '#2BBA52',
    backgroundColor: '#2BBA521A',
  },
});
