import { StyleSheet } from 'react-native';
import { Tokens } from '../../theme/theme';


export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#E0E5EC',
  },
  safeArea: {
    flex: 1,
  },
  scrollContainer: {
    alignItems: 'center',
  },
  mainContainer: {
    width: '100%',
    maxWidth: Tokens.layout.maxWidth,
    paddingVertical: Tokens.layout.paddingVertical,
    paddingHorizontal: Tokens.layout.paddingHorizontal,
    alignItems: 'center',
  },
  header: {
    width: '100%',
    marginBottom: Tokens.gaps.separator,
    gap: Tokens.gaps.large,
  },
  titleText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.title,
    lineHeight: Tokens.typography.lineHeights.title,
    color: '#3D4852',
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  subtitleText: {
    fontFamily: Tokens.typography.families.light,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#6B7280',
  },
  inputFieldsContainer: {
    width: '100%',
    gap: Tokens.gaps.xlarge,
    marginBottom: Tokens.gaps.section,
  },
  inputOuterView: {
    width: '100%',
    height: Tokens.components.inputHeight,
    borderRadius: 16,
    backgroundColor: '#E0E5EC',
    overflow: 'hidden',
    // Neumorphic inset simulation
    borderWidth: 1,
    borderColor: 'rgba(163, 177, 198, 0.25)',
  },
  inputInnerContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    backgroundColor: 'rgba(163, 177, 198, 0.08)',
    borderRadius: 16,
  },
  inputGradientBackground: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    backgroundColor: 'rgba(163, 177, 198, 0.08)',
    borderRadius: 16,
  },
  inputText: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.body,
    color: '#3D4852',
    height: '100%',
  },
  passwordView: {
    width: '100%',
    gap: Tokens.gaps.large,
  },
  eyeButton: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: Tokens.gaps.small,
  },
  strengthView: {
    width: '100%',
    gap: Tokens.gaps.small,
  },
  strengthTextRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 24,
  },
  passwordStrengthText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#3D4852',
  },
  strongValueText: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#6B7280',
  },
  navigationMeterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 16,
    gap: 6,
  },
  meterBar: {
    flex: 1,
    height: Tokens.components.barMetricHeight,
    borderRadius: 8,
    backgroundColor: '#E0E5EC',
    // Neumorphic small extruded for bars
    shadowColor: 'rgb(163, 177, 198)',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 2,
  },
  requirementView: {
    width: '100%',
    gap: Tokens.gaps.medium,
    marginTop: Tokens.gaps.small,
  },
  requirementText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#3D4852',
  },
  indicationView: {
    width: '100%',
    gap: Tokens.gaps.small,
  },
  indicationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Tokens.gaps.small,
    height: 20,
  },
  iconBoxCenter: {
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  requirementItemText: {
    fontFamily: Tokens.typography.families.regular,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#6B7280',
  },
  infoBarView: {
    width: '100%',
    minHeight: Tokens.components.infoMinHeight,
    borderRadius: 16,
    overflow: 'hidden',
  },
  infoBarInnerView: {
    flex: 1,
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(108, 99, 255, 0.08)',
  },
  infoIconSpacing: {
    marginRight: Tokens.gaps.medium,
  },
  infoBarText: {
    flex: 1,
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#3D4852',
  },
  inputView: {
    width: '100%',
    gap: Tokens.gaps.small,
  },
  passwordMatchedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    height: 20,
    paddingHorizontal: 4,
  },
  passwordMatchedText: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.small,
    lineHeight: Tokens.typography.lineHeights.small,
    color: '#6B7280',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Tokens.gaps.small,
    width: '100%',
    height: 24,
    marginTop: Tokens.gaps.small,
  },
  checkmarkBoxActive: {
    width: 24,
    height: 24,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6C63FF',
    // Neumorphic small extruded
    shadowColor: 'rgb(163, 177, 198)',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 3,
  },
  checkmarkBoxInactive: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: '#E0E5EC',
    // Neumorphic inset
    borderWidth: 1,
    borderColor: 'rgba(163, 177, 198, 0.3)',
  },
  checkboxLabel: {
    fontFamily: Tokens.typography.families.medium,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#3D4852',
  },
  continueButtonView: {
    width: '100%',
    gap: Tokens.gaps.large,
    alignItems: 'center',
  },
  primaryButtonWrapper: {
    width: '100%',
    height: Tokens.components.buttonHeight,
    borderRadius: 16,
    shadowColor: 'rgb(163, 177, 198)',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 6,
  },
  primaryButton: {
    flex: 1,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6C63FF',
  },
  primaryButtonText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.subButton,
    lineHeight: Tokens.typography.lineHeights.title,
    color: '#FFFFFF',
  },
  socialsView: {
    width: '100%',
    gap: Tokens.gaps.large,
    alignItems: 'center',
  },
  orSignUpWithText: {
    fontFamily: Tokens.typography.families.regular,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#6B7280',
    marginVertical: 4,
  },
  socialButton: {
    width: '100%',
    height: Tokens.components.buttonHeight,
    backgroundColor: '#E0E5EC',
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgb(163, 177, 198)',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 6,
  },
  socialIconLayout: {
    marginRight: 8,
  },
  socialButtonText: {
    fontFamily: Tokens.typography.families.semiBold,
    fontSize: Tokens.typography.sizes.subButton,
    lineHeight: Tokens.typography.lineHeights.title,
    color: '#3D4852',
  },
  footerView: {
    width: '100%',
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    flexDirection: 'row',
  },
  loginText: {
    marginTop: 7,
  },
  footerText: {
    fontFamily: Tokens.typography.families.regular,
    fontSize: Tokens.typography.sizes.body,
    lineHeight: Tokens.typography.lineHeights.body,
    color: '#3D4852',
    textAlign: 'center',
  },
  loginLink: {
    fontFamily: Tokens.typography.families.semiBold,
    textDecorationLine: 'underline',
    color: '#6C63FF',
  },
  checkmarkCircleWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: '#38B2AC',
    backgroundColor: 'rgba(56, 178, 172, 0.1)',
  },
});
